services:
  crypto-analyzer-analysis:
    image: node:18-alpine
    container_name: crypto-analyzer-analysis
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password123@mongodb-search:27017/searchResults?authSource=admin
    command: sh -c "npm install && npm run start"
    networks:
      - crypto_network 