services:
  crypto-analyzer-analysis:
    image: node:18-alpine
    container_name: crypto-analyzer-analysis
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    env_file:
      - .env
    command: sh -c "npm install && npm run start"
    networks:
      - crypto_network 